FOODSITE_PROJECT/FOODSITE_PROJECT/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    
    
]

FOODSITE_PROJECT/food/urls.py
from django.urls import path
from . import views


app_name= 'food'

urlpatterns = [
    path('greet/', views.greet, name='greet'),
    path('process/', views.process,name='process'),
    path('', views.item,name="item"),
    path('<int:item_id>/', views.detail, name='detail'),
    path('add/', views.add_item,name="add_item"),
    path('update/<int:id>/', views.update_item,name="update_item"),
    path('delete/<int:id>/', views.delete_item,name="delete_item"),
    
    
]

FOODSITE_PROJECT/food/models.py
from django.db import models

# Create your models/class here.
class Item(models.Model):
    
    item_name=models.CharField(max_length=50)
    item_desc=models.CharField(max_length=100)
    item_price=models.FloatField()
    item_image=models.CharField(max_length=500,default="https://cdn-icons-png.flaticon.com/512/1147/1147805.png")

    #to get the items name instead object
    def __str__(self):
        return self.item_name
  
    

FOODSITE_PROJECT/food/forms.py

from django import forms
# from .models import Item
from  .models import Item

class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ["item_name","item_desc","item_price"]



FOODSITE_PROJECT/food/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.template import loader
from . import forms
from . import models



from food.models import Item


# Create your views here.
def greet(resquest):
    return HttpResponse("This is DJango APp!")

def process(request):
    return HttpResponse("We are processing the request!")

def item(request):
    item_list=Item.objects.all()  #data
    # temp=loader.get_template('food/index.html')  #template
    context={
        'item_list': item_list
    }
    return render(request,'food/index.html',context)

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'food/item_detail.html',context)

def add_item(request):
    form=forms.ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("food:item")
    
    return render(request,'food/item_form.html',context={'form':form})

def update_item(request,id):
    item=Item.objects.get(id=id)
    form=forms.ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:item")
    
    return render(request,'food/item_form.html', context={'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)
    form=forms.ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:item")
    
    return render(request,'food/item_form.html', context={'form':form,'item':item})

   



FOODSITE_PROJECT/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FOODSITE</title>
    
    
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js">
    <link href="../../static/food/index_style.css" rel="stylesheet">
</head>
<body>
     <nav class ="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" style="margin-left: 10px; margin-right: 10px" href="http://127.0.0.1:8000/food/add/"><h6 style=color:azure>Add Item</h6></a>
            <a class="nav-item nav-link" style="margin-left: 10px; margin-right: 10px" href="#"><h6 style=color:brown>Delete Item</h6></a>
            <a class="nav-item nav-link" style="margin-left: 10px; margin-right: 10px" href="#"><h6 style=color:blueviolet>View Item</h6></a>
        </div>

        
     </nav>
    {% block body %}
    {% endblock %}
 </body>
 </html>   

FOODSITE_PROJECT/food/templates/food/index.html
{%  extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FOODSITE</title>
    {% comment %} <link href="../../static/food/index_style.css" rel="stylesheet"> {% endcomment %}
</head>
<body>
    {% block body %}
    {% for item in item_list %}
      <div class="row" style="border:1px solid lightgray;">
        <div class="col-md-3 offset md-1">
          <img src="../../static/food/{{item.item_name}}.jpg" width="150px" height="120px" class="image_class"></div>
        <div class="col-md-2">
          <h3 style="margin-top:20px">{{item.item_name}}</h3>
          {% comment %} <h4>{{item.item_desc}}</h4> {% endcomment %}
          <h5>${{item.item_price}}</h5>
        </div>
        
        <div class="col-md-3">
          <a href="{% url 'food:detail' item.id %}">
           <button class ="btn btn-success" style="margin-top:50px">View Detail</button></a>
      </div> 
      <div class="col-md-3">
        <a href="{% url 'food:update_item' item.id %}">
          <button class ="btn btn-primary" style="margin-top:50px">Update</button></a>
        </div>
    </div>


    
      











    {%endfor%}
    {% endblock%}
</body>
</html>

FOODSITE_PROJECT/food/templates/food/item_detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container w-100" style="margin-top:30px">
    <div class="row">
        <div class="col-md-3">
            
            <img src="../../static/food/{{item.item_name}}.jpg" width="250px" height="150px" class="image_class">

        </div>
        <div class="col-md-3 offset md-2" style="margin-left:20px">
            <p>{{item.item_desc}}</p>
            
             
            

        </div>
        <div class="col-md-3" >
            <button  class="btn btn-primary" style="margin-top:80px; width:120px">Add</button></div>

    </div>
</div>



{% endblock %}






FOODSITE_PROJECT/food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}
<div class ="abc" style="margin-top:30px">
  <form method="POST">
    {% csrf_token %}
    {{form}}
    <button  class="btn btn-primary" type="submit">save</button>

  </form>

</div>
{% endblock %}

FOODSITE_PROJECT/food/templates/food/rough.html
{% extends 'food/base.html' %}

{% block body %}
<h1> testing</h1>
  {% for i in item%}
  <h2>{{i.item_name}}</h2>
  {% endfor %}
{% endblock %}